### ISSUE TITLE
Trouble using email.query()

### ISSUE THREAD

**Issue by foviestar** [maxnaude/pardot-api-client#2]
I've been able to successfully query many of the other objects in the API using this library, but email is giving me some troubles.

The expression: _client.email.query()_ 
Throws the following error: **AttributeError: 'str' object has no attribute 'query'**

I think it has something to do with the authentication component having a property of "email" as in:
client = APIClient(**email**=myUsername, password=myPassword, user_key=myToken)

Has anyone been able to get the email object to query? If so, how did you do it?

Thanks

**Comment by maxnaude** [comment]
@foviestar the only operation that the email endpoint on the Pardot API supports is read (no query):  http://developer.pardot.com/kb/api-version-3/emails/

**Comment by maxnaude** [comment]
@foviestar can we close this?

**Comment by foviestar** [comment]
Yes
